{{- if .Values.serviceAccount.create }}
{{- range $manager, $config := .Values.managers }}
{{- if $config.enabled }}
{{- $ctx := dict "root" $ "manager" $manager }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "router-api.managerName" $ctx }}
  labels:
    {{- include "router-api.labels" $ctx | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
